Tạo ví dụ Hello World

In [3]:
import numpy as np 
my_array = np.array([1,2,3,4])
print("Mang moi khoi tao")
print(my_array)

my_arange = np.arange(10)
print(my_arange[3])

Mang moi khoi tao
[1 2 3 4]
3


In [4]:
print(my_arange.shape)

(10,)


In [8]:
my_matrix = np.array([[1,2,3],[4,5,6]])
print(my_matrix)
print(my_matrix.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [10]:
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])
sum_vector = vector1 + vector2
print(vector1)
print(vector2)
print()
print(sum_vector)


[1 2 3]
[4 5 6]

[5 7 9]


In [14]:
matrix1 = np.array([[1,2,3],[4,5,6]])
matrix2 = np.array([[7,8,9],[10,11,12]])
sum_matrix = matrix1 + matrix2
print(matrix1 )
print()
print(matrix2 )
print()
print(sum_matrix)

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]]

[[ 8 10 12]
 [14 16 18]]


In [ ]:
dot_vector = np.dot(vector1,vector2)
dot_matrix = np.dot(matrix1,vector1)
print(dot_vector)
print()
print(dot_matrix)


[14 32]
