In [ ]:
import numpy as np
x = np.int8(10)
print(x,x.dtype)
print(x*3)

In [ ]:
my_vactor = np.array([1,2,3,4],dtype = np.int8)
print(my_vactor[3], my_vactor[3].dtype)

In [ ]:
date_array = np.array(['2025-10-12','10-12-2025'],dtype=np.datetime64)
print(date_array)
# print(date_array[0].dtype,date_array[1].dtype )

1.8 Kiểu tự định nghĩa
NumPy cho phép người dùng định nghĩa và sử dụng các kiểu dữ 
liệu tùy chỉnh thông qua np.dtype
13


In [ ]:
import numpy as np
student_dtype = np.dtype([('name',np.str_,20),('age',np.int32),('grade',np.int32)])
students = np.array([('An',20,6),('Binh',25,9)],dtype=student_dtype)
print(students)
print(students[0])
print(students.dtype)
print(students.shape)

In [ ]:
print(students[0]['grade'])

In [ ]:
print(students.ndim)

In [ ]:
my_matrix = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                      [[1,2,3],[4,5,6],[7,8,9]]])
print(my_matrix)
print(my_matrix.shape)
print(my_matrix.ndim)

Phân biệt List và Tuple

In [12]:
import numpy as np
my_list = [1,3,5]
my_tuple = (2,4,6)

print(list)
print(tuple)


[1, 3, 5, 7, 7]
(2, 4, 6)


In [14]:
array_list = np.array(my_list)
array_tuple = np.array(my_tuple)

print(list)
print(tuple)
print(array_list)
print(array_tuple)

[1, 3, 5, 7, 7]
(2, 4, 6)
[1 3 5]
[2 4 6]


In [17]:
my_array_random = np.random.rand(2,2)
my_array_random_int = np.random.randint(0,10,5)

print(my_array_random)
print(my_array_random.shape)
print(my_array_random_int)
print(my_array_random_int.shape)

[[0.82287095 0.85068421]
 [0.4665957  0.12780119]]
(2, 2)
[6 6 0 2 4]
(5,)


In [ ]:
import numpy as np
my_arange1  = np.arange(0,10,2)
print(my_arange1)

my_arange2  = np.arange(20)
print(my_arange2)

my_arange3  = np.linspace(0,10)
print(my_arange3)


[ 0  2  4  6  8 10 12 14 16 18]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0.          0.40816327  0.81632653  1.2244898   1.63265306  2.04081633
  2.44897959  2.85714286  3.26530612  3.67346939  4.08163265  4.48979592
  4.89795918  5.30612245  5.71428571  6.12244898  6.53061224  6.93877551
  7.34693878  7.75510204  8.16326531  8.57142857  8.97959184  9.3877551
  9.79591837 10.20408163 10.6122449  11.02040816 11.42857143 11.83673469
 12.24489796 12.65306122 13.06122449 13.46938776 13.87755102 14.28571429
 14.69387755 15.10204082 15.51020408 15.91836735 16.32653061 16.73469388
 17.14285714 17.55102041 17.95918367 18.36734694 18.7755102  19.18367347
 19.59183673 20.        ]
